### PR TITLE
Folders checkbox fix issue 46 / Bug 5770

### LINKED ISSUE #46: Folders within a dynamic map service are not toggled on when user selects Turn On All Sublayers (nor off)
__How often can you reproduce it?__ 

Always

__Description:__

If a dynamic map service contains folders, e.g. Critical Lands and Waters Identification Project (CLIP), the options to toggle sublayers do not affect the folders, only the layers within the folders. So if you have the CLIP_V4 and CLIP Opportunities folders unchecked, and select Turn on All Sublayers, the layers within the folders are checked, but not their parent folder, and so the layers are still effectively not visible.

__Steps to reproduce:__

1. Add any map service that has folders, such as the CLIP service (under Wildlife and Habitat)
2. Turn off the folders by unchecking each checkbox next to a folder icon.
3. Select Turn On All Sublayers menu option from the layer's "hamburger" menu

__Expected results:__
All layers and folders are checked and visible

__Actual results:__
All layers are checked, but the folders that were unchecked in step 2 remain unchecked, so layers within the folders are not visible in the map.

### PR DESCRIPTION
**Pull request by wmbeers**
# Description
Adding loop through folders to the same function that loops through layers to toggle visibility.

### CODE REVIEW

**Review by mikekonikoff — COMMENTED** [review]
Changes look good! Forwarding for approval.

**Review by mikekonikoff — APPROVED** [review]
Change request has been approved

**Comment by wmbeers** [comment]
Deployed and verified on preprod and prod.

**Comment by wmbeers** [comment]
Merged to public site.

**Pull request merged**
